// ignore_for_file: invalid_annotation_target

import 'package:freezed_annotation/freezed_annotation.dart';

import '../../../../core/utils/json_parsers.dart';
import '../../domain/entities/order_info_entity.dart';

part 'order_info_model.freezed.dart';
part 'order_info_model.g.dart';

/// Data-layer representation of an order line item.
///
/// RULES:
///  - Models do NOT extend entities. They implement [toEntity] to map.
///  - All JSON handling lives here (generated by `json_serializable`).
///  - Unknown/missing fields must have defaults; the domain layer never
///    receives null where an entity default exists.
@freezed
abstract class OrderInfoModel with _$OrderInfoModel {
  const OrderInfoModel._();

  const factory OrderInfoModel({
    String? barCode,
    String? orderId,
    String? iconStatus,
    @JsonKey(name: 'productId', fromJson: parseToInt) @Default(0) int productId,
    String? hsBrandLabel,
    @Default('') String productName,
    String? productImageUrl,
    String? productSize,
    @Default(0) int orderItemId,
    @Default(0) int itemCounts,
    @Default(0.0) double amount,
    DeliveryMessageInfoModel? deliveryMessage,
    ReturnInfoMessageModel? returnTagMessage,
    @Default(false) bool isGift,
  }) = _OrderInfoModel;

  factory OrderInfoModel.fromJson(Map<String, dynamic> json) =>
      _$OrderInfoModelFromJson(json);

  OrderInfoEntity toEntity() => OrderInfoEntity(
    barCode: barCode,
    orderId: orderId,
    iconStatus: iconStatus,
    productId: productId,
    hsBrandLabel: hsBrandLabel,
    productName: productName,
    productImageUrl: productImageUrl,
    productSize: productSize,
    orderItemId: orderItemId,
    itemCounts: itemCounts,
    amount: amount,
    deliveryMessage: deliveryMessage?.toEntity(),
    returnTagMessage: returnTagMessage?.toEntity(),
    isGift: isGift,
  );
}

@freezed
abstract class DeliveryMessageInfoModel with _$DeliveryMessageInfoModel {
  const DeliveryMessageInfoModel._();

  const factory DeliveryMessageInfoModel({
    String? deliveryMessage,
    String? orderItemActionMessage,
    String? secondaryMessage,
    String? delayedDeliveryMessage,
    String? previousEstimatedDeliveryDate,
    String? color,
  }) = _DeliveryMessageInfoModel;

  factory DeliveryMessageInfoModel.fromJson(Map<String, dynamic> json) =>
      _$DeliveryMessageInfoModelFromJson(json);

  DeliveryMessageInfoEntity toEntity() => DeliveryMessageInfoEntity(
    deliveryMessage: deliveryMessage,
    orderItemActionMessage: orderItemActionMessage,
    secondaryMessage: secondaryMessage,
    delayedDeliveryMessage: delayedDeliveryMessage,
    previousEstimatedDeliveryDate: previousEstimatedDeliveryDate,
    color: color,
  );
}

@freezed
abstract class ReturnInfoMessageModel with _$ReturnInfoMessageModel {
  const ReturnInfoMessageModel._();

  const factory ReturnInfoMessageModel({
    @Default(false) bool qcAndWrTagSuccess,
    String? mobileNumber,
    String? message,
  }) = _ReturnInfoMessageModel;

  factory ReturnInfoMessageModel.fromJson(Map<String, dynamic> json) =>
      _$ReturnInfoMessageModelFromJson(json);

  ReturnInfoMessageEntity toEntity() => ReturnInfoMessageEntity(
    qcAndWrTagSuccess: qcAndWrTagSuccess,
    mobileNumber: mobileNumber,
    message: message,
  );
}
