// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkVMmtboaehvQ-tNchKkDlzDsGR5JYjlA',
    appId: '1:645600819281:web:f8fa6ea9fc2b9ef349a070',
    messagingSenderId: '645600819281',
    projectId: 'hs-app-flutter',
    authDomain: 'hs-app-flutter.firebaseapp.com',
    storageBucket: 'hs-app-flutter.firebasestorage.app',
    measurementId: 'G-P3LPV33ZHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBng2y9mafF1ARbr6b5ANeJqUuLzs75h6I',
    appId: '1:645600819281:android:e618ecc14b4118c849a070',
    messagingSenderId: '645600819281',
    projectId: 'hs-app-flutter',
    storageBucket: 'hs-app-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7agsqzsCoyr5hruHqIoO95Xp3nJJePS8',
    appId: '1:645600819281:ios:c1c6acb94446b90249a070',
    messagingSenderId: '645600819281',
    projectId: 'hs-app-flutter',
    storageBucket: 'hs-app-flutter.firebasestorage.app',
    iosBundleId: 'in.hopscotch.hopscotch.new',
  );
}
